import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HeaderMenuBar } from "@/components/header-menubar";
import { SlideShow } from "@/components/slide-show";
import styles from "./layout.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Celon Travel Life",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header>
        <HeaderMenuBar />
      </header>
      <div className={styles["image-container"]}>
        <SlideShow />
        <div className={styles["headline"]}>
          <p className={styles["line1"]}>Your</p>
          <p className={styles["line2"]}>Travel</p>
          <p className={styles["line3"]}>Companion</p>
        </div>
      </div>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
