import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HeaderMenuBar } from "@/components/header-menubar";
import { SlideShow } from "@/components/slide-show";
import styles from "./layout.module.css";

// Font configuration
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for SEO
export const metadata: Metadata = {
  title: "Celon Travel Life",
  description: "Generated by create next app",
};

// Root Layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header inside body */}
        <header>
          <HeaderMenuBar />
        </header>

        {/* Slideshow section */}
        <div className={styles["image-container"]}>
          <SlideShow />
          <div className={styles["headline"]}>
            <p className={styles["line1"]}>Your</p>
            <p className={styles["line2"]}>Travel</p>
            <p className={styles["line3"]}>Companion</p>
          </div>
        </div>

        {/* Main Content */}
        <main>{children}</main>
      </body>
    </html>
  );
}
