pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = 'docker-cred' // Docker Hub credentials ID
        DOCKER_REPO_BACKEND = 'logicloom2/ceylontravellife-backend'
    }


    stages {
        stage('Checkout Code') {
            steps {
                // Pull the latest code from the Git repository
                git branch: 'main', url: 'https://github.com/dltmthilina/travel-srilanka'
            }
        }

        stage('Check Changes in Backend') {
            steps {
                script {
                    def changes = bat(script: 'git diff --name-only HEAD~1 HEAD', returnStdout: true).trim()
                    if (!changes.contains('backend/')) {
                        echo "No changes in backend. Skipping build."
                        currentBuild.result = 'SUCCESS'
                        error("Skipping build since no backend changes detected.")
                    }
                }
            }
        }


        stage('Build Backend Image') {
            steps {
                script {
                    def imageTag = "latest"
                    // Navigate to the backend folder and build Docker image
                    bat "cd backend && docker build -t %DOCKER_REPO_BACKEND%:latest ."
                }
            }
        }

        stage('Push Backend Image') {
            steps {
                script {
                    // Login to Docker Hub and push the backend image
                    withDockerRegistry([credentialsId: DOCKERHUB_CREDENTIALS, url: '']) {
                        retry(3) { // Retry up to 3 times
                                 bat "docker push %DOCKER_REPO_BACKEND%:latest"
                        }
                        
                    }
                }
            }
        }

    }

    post {
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
